config/routes.rb
Rails.application.routes.draw do
  resources :collections
  get "/show", to: "slideshow#show"

  get "/album", to: "album#album"
  get "/album/photo", to: "album#photo"

  get "/about", to: "about#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homepage#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  validates :name, presence: true
  validates :picture, presence: true, format: {with: /\A.+\.((jpg)|(JPG))\Z/}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/album_controller.rb
class AlbumController < ApplicationController
  def album
    @albums = Collection.all
    @album_names = Collection.select(:name).distinct
  end

  def photo 
    selected_album = params[:album_name]
    @photos = Collection.where(name: selected_album)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
    @album_names = Collection.select(:name).distinct
    @all_pic_array = Dir.glob("*.{jpg,JPG}", base: "app/assets/images")
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :picture, :description)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
    @all_pic_array = Dir.glob("*.{jpg,JPG}", base: "app/assets/images")
  end
end

app/controllers/slideshow_controller.rb
class SlideshowController < ApplicationController
  def show
    pic_array = Dir.glob("*.{jpg,JPG}", base: "app/assets/images")
    rand_number = rand(pic_array.length)
    @rand_pic = pic_array[rand_number]
    if Collection.exists?(:picture => @rand_pic)
      rand_pic_record = Collection.find_by(picture: @rand_pic)
      @rand_pic_desc = rand_pic_record.description
    else
      @rand_pic_desc = @rand_pic + ', randomly selected'
    end
  end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/slideshow_helper.rb
module SlideshowHelper
end

app/views/about/about.html.erb
<% @title="About" %>

<h1 class="font_handwriting">About</h1>

<p>One functionality that is worth taking a look at is on the slideshow page. This page displays an image randomly selected from the <i>app/assets/images</i> folder. The selection of the picture occurs every time the site is visited, so users encounter a different image every time. The implementation of this functionality includes fetching data from database, getting jpeg files in the specified folder, choosing a random picture, and testing the randomness. Other functionalities such as managing albums, showing pictures and albums, and forms to modify data in database require knowledge of Active Record, Rails, Ruby, and CSS. This individual project successfully integrates multiple aspects of web technologies and provide online photo gallery.</p>

app/views/album/album.html.erb
<% @title="Album" %>

<h1 class="font_handwriting">Album</h1>

<p>This page shows albums organized by the <i>collection</i> table in database. You can see pictures in the album by clicking on a picture.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dapibus vulputate sapien, sed porttitor risus vehicula vitae. Cras non imperdiet sapien. Nulla et urna sed est faucibus sollicitudin in et mauris. Nam condimentum, mauris ac placerat ullamcorper, quam metus dictum odio, in fringilla erat ex a urna. Aenean faucibus pharetra nulla, ut condimentum nulla suscipit at. Duis justo lacus, molestie eget placerat ut, pellentesque suscipit felis. Aliquam purus neque, porta ut interdum non, suscipit quis purus. Sed aliquet auctor risus vitae condimentum.</p>

<div class="container">
  <% col_count = 0 %>
  <% @album_names.each do |album| %>
    <% if col_count % 4 == 0 %>
      <div class="row">
    <% end %>
    <div class="col-sm-3">
      <% albumName = album[:name] %>
      <% albumId = @albums.find_by(name: albumName) %>
      <h2 class="font_display"><%= albumName %></h2>
      <% coverPhoto = Collection.find_by(name: albumName)[:picture] %>
      <% coverPhotoDesc = Collection.find_by(name: albumName)[:description] %>
      <%= link_to image_tag(coverPhoto, class: "img-thumbnail img-fluid", alt: coverPhotoDesc), album_photo_path(album_name: albumName)  %>
    </div>
    <% if col_count % 4 == 3 %>
      </div>
    <% end %>
    <% col_count += 1 %>
  <% end %>
</div>

app/views/album/photo.html.erb
<% @title="Photo" %>

<h1 class="font_handwriting">Photos</h1>

<p>This page shows photos in the album. The description is provided below the picture name.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar eros tincidunt nisl ultrices porta. Vivamus justo nulla, eleifend eu urna eget, blandit sodales magna. Mauris sed nisi et nulla tempor laoreet. Praesent tincidunt turpis ac libero ullamcorper sodales. Donec varius sem et euismod volutpat. Maecenas auctor ullamcorper lacus, et pretium ex interdum sed. Suspendisse euismod erat ex, id convallis tortor tempor in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis elit nisl, dignissim ut scelerisque eu, scelerisque id augue.</p>

<div class="container">
  <% col_count = 0 %>
  <% @photos.each do |photo| %>
    <% if col_count % 4 == 0 %>
      <div class="row">
    <% end %>
    <div class="col-sm-3">
      <%= link_to image_tag(photo[:picture], class: "img-thumbnail img-fluid", alt: photo[:description]), image_path(photo[:picture]) %>
      <p><%= photo[:picture] %></p>
      <p><%= photo[:description] %></p>
    </div>
    <% if col_count % 4 == 3 %>
      </div>
    <% end %>
    <% col_count += 1 %>
  <% end %>
</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection, local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Select album" %>
    <!-- <%= form.text_field :name, id: :collection_name %> -->
    <%= form.collection_select :name, Collection.select(:name).distinct, :name, :name, {:prompt => 'Please select the album'}, id: :collection_name %>
  </div>

  <div class="field">
    <%= form.label :picture, "Select picture" %>
    <!-- <%= form.text_field :picture, id: :collection_picture %> -->
    <%= form.select :picture, Dir.glob("*.{jpg,JPG}", base: "app/assets/images").map{|u| [u, u]}, {}, id: :collection_picture %>
  </div>

  <div class="field">
    <%= form.label :description, "Enter description" %>
    <%= form.text_field :description, id: :collection_description %>
  </div>

  <div class="actions">
    <%= form.submit "Updata Album"%>
  </div>
<% end %>

app/views/collections/_form_new.html.erb
<%= form_with(model: collection, local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Enter new album name" %>
    <%= form.text_field :name, id: :collection_name %>
  </div>

  <div class="field">
    <%= form.label :picture, "Select cover picture"%>
    <%= form.select :picture, Dir.glob("*.{jpg,JPG}", base: "app/assets/images").map{|u| [u, u]}, {:prompt => 'Please select a cover picture'}, id: :collection_picture %>
  </div>

  <div class="field">
    <%= form.label :description, "Enter description"%>
    <%= form.text_field :description, id: :collection_description %>
  </div>

  <div class="actions">
    <%= form.submit "Create an album"%>
  </div>
<% end %>

app/views/collections/edit.html.erb
<% @title="Edit Album" %>
<h1>Edit Album</h1>

<p>You can edit update the album on this page by providing the album name, the picture name, and the description.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut risus justo. Sed facilisis nulla sit amet nibh sagittis, et consectetur diam commodo. Integer gravida pellentesque turpis vitae venenatis. Vestibulum lobortis, arcu ac venenatis sagittis, augue arcu ornare tellus, at euismod magna lorem ac lacus. Duis a ligula pretium, sagittis enim condimentum, consectetur nisi. Donec vestibulum dignissim arcu sit amet venenatis. Etiam suscipit hendrerit justo, vel semper orci pretium at. Fusce sed risus rhoncus, condimentum nisi vel, malesuada nibh. Nam aliquet metus pharetra, fermentum odio ac, eleifend odio. Nulla in varius risus. Vivamus mattis purus vitae massa euismod, vestibulum consectetur sapien porta. Vivamus dictum bibendum consequat. Sed at dui eget ipsum cursus dapibus. Etiam feugiat quam viverra vehicula vulputate. Donec interdum finibus tellus a semper. Sed vitae pulvinar tortor, eu fringilla tellus.</p>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<% @title="Collection" %>

<p id="notice"><%= notice %></p>

<h1 class="font_handwriting">Collections</h1>

<p>This page lets you create, read, update, and delete albums. You can organize pictures on this page.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet tempus ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus enim justo, semper sit amet consequat non, egestas at libero. Phasellus vestibulum sit amet lectus vitae bibendum. In hac habitasse platea dictumst. Suspendisse turpis dui, porttitor nec pretium eu, aliquam sed tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi ut mattis risus. Vestibulum rhoncus nulla sed ultricies auctor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras suscipit nunc et nibh posuere, at rhoncus sem aliquet. Vestibulum luctus facilisis lacus, vitae eleifend erat dapibus a. Quisque ex lectus, dictum a ullamcorper in, pellentesque a metus. Ut tempus, augue sit amet aliquet finibus, sapien nulla interdum purus, ac mattis justo ex at sem. Pellentesque viverra lorem ac lorem pharetra gravida eu nec nisi.</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th colspan="3">Control</th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= link_to collection.picture, image_path(collection.picture) %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Delete', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_collection_path %>

<br>

app/views/collections/new.html.erb
<% @title="New Album" %>

<h1>New Album</h1>

<p>This page allows you to create a new album. Just provide the name of a new album and a picture, and the description.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed egestas euismod orci. Donec sit amet velit blandit, ornare ligula ut, aliquet elit. Etiam eget lectus sapien. Aliquam sed orci in ante lacinia fringilla venenatis luctus quam. Etiam maximus efficitur tempus. In hac habitasse platea dictumst. Nullam sagittis augue id turpis ultrices, ut porttitor mi scelerisque. Cras volutpat vestibulum velit, hendrerit tempor justo ornare nec. Sed at accumsan turpis, quis tincidunt sapien. Sed metus velit, interdum id dolor sit amet, tincidunt elementum mi.</p>

<%= render 'form_new', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<% @title="Show" %>

<p id="notice"><%= notice %></p>

<p>This page displays the name of the picture, which album it belongs to, the description, and the image.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non leo et massa porttitor dignissim. Mauris nec ipsum a dolor faucibus ultrices et eget sapien. Morbi finibus fermentum nisl vel fermentum. Nulla quis felis lacus. Pellentesque sodales, risus vel ornare sagittis, urna nisi consequat ligula, et blandit risus turpis a arcu. Nullam consequat purus purus, in fermentum est eleifend non. Vestibulum imperdiet libero vel nibh dapibus pharetra.</p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @collection.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @collection.description %>
</p>

<%= image_tag(@collection.picture, class: "img-thumbnail img-fluid", alt: @collection.description) %>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>

app/views/homepage/home.html.erb
<% @title="Home" %>

<h1 class="font_handwriting">Photos</h1>

<p>This page shows all the pictures contained in <i>app/assets/imagesi</i> folder. If description is provided in the <i>collection</i> database, it will appear below the picture name. Otherwise, it will read "No description."</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper, sem non ornare consectetur, dui elit faucibus neque, sit amet rhoncus massa metus in lacus. Vestibulum vestibulum quam quis leo lobortis hendrerit. Pellentesque bibendum pharetra congue. Cras pulvinar faucibus sem, sed feugiat nunc consectetur et. Praesent in mi sed nunc efficitur congue eget vel urna. Maecenas odio tellus, venenatis sit amet tellus eu, accumsan faucibus est. Nullam pellentesque mauris sit amet volutpat tristique.</p>

<div class="container">
  <% col_count = 0 %>
  <% @all_pic_array.each do |image| %>
    <% if Collection.exists?(:picture => image) %>
      <% image_record = Collection.find_by(picture: image) %>
      <% image_desc = image_record.description %>
    <% else %>
      <% image_desc = 'No description' %>
    <% end %>

    <% if col_count % 4 == 0 %>
      <div class="row">
    <% end %>
    <div class="col-sm-3">
      <%= link_to image_tag(image, class: "img-thumbnail img-fluid", alt: image_desc), image_path(image) %>
      <p><%= image %><br><%= image_desc %></p>
    </div>
    <% if col_count % 4 == 3 %>
      </div>
    <% end %>
    <% col_count += 1 %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @title %> | Gallery</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <!-- <%= link_to "gallery", root_path, id: "logo" %> -->
        <h1 id="logo">gallery</h1>
        <nav>
          <ul class="nav navbar-nav navbar-right font_handwriting" id="nav_bar_font">
            <!-- <li><a class="skip-main" href="#main">Skip to main content</a></li> -->
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Album",   album_path %></li>
            <li><%= link_to "Edit",   collections_path %></li>
            <li><%= link_to "Slide Show", show_path %></li>
            <li><%= link_to "About", about_path %></li>
          </ul>
        </nav>
      </div>
    </header>

    <div style="padding-bottom: 1em;" class="container" id="main">
      <%= yield %>
    </div>

    <footer class="navbar navbar-fixed-bottom navbar-inverse">
    <!-- Copyright -->
      <div class="container">
        <p class="navbar-text">© 2019 Copyright: Kohei Kotani</p>
      </div>
    <!-- Copyright -->
    </footer>
  </body>
</html>

app/views/slideshow/show.html.erb
<% @title="Slideshow" %>

<h1 class="font_handwriting">Slideshow</h1>

<p>This page shows a random picture in the <i>app/assets/images</i> folder. Enjoy a variety of photos you have!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec lacus varius metus porttitor dapibus. Aenean in condimentum erat. Sed vehicula sem justo, ac ultricies dui sollicitudin ac. Nulla et nunc sodales, eleifend eros at, elementum nulla. Nulla tincidunt arcu eu urna condimentum, eget iaculis purus tristique. Proin vitae sapien quis tortor efficitur sollicitudin. Donec diam orci, elementum vitae lacinia vitae, ullamcorper eget ligula. Mauris luctus sit amet ante nec bibendum. Donec tristique porttitor tristique.</p>

<h2 class="font_sanserif">Photo of the Visit</h2>
<%= link_to image_tag(@rand_pic, class: "img-thumbnail img-fluid", alt: @rand_pic_desc), image_path(@rand_pic) %>